### ISSUE TITLE
Provide release version

### ISSUE THREAD

**Issue by LinArcX** [Canop/clima#4]
Hi. i'm eager to create a package for your tool for void-linux. But they only accept release versions of packages. So, please provide release version. Thanks.

**Comment by Canop** [comment]
Hi @LinArcX can you please come and discuss this in Miaou: https://miaou.dystroy.org/3

I'd especially like to check you know that clima is *not* a general purpose markdown viewer.

**Comment by LinArcX** [comment]
Hmm.. why not?
I wanted to wrap it as a vim plugin in future. :) So sad to hear it.

**Comment by Canop** [comment]
clima is based on termimad, whose main purpose is to help build cli applications. Its support of markdown is limited because the markdown you specifically write for cli applications is usually simpler.

You *may* use it as a general purpose markdown tool if you want but there are probably better tools for that (I didn't search, TBH).

This being said... I'd be curious to see such integration into vim as I must wrap broot in vim...

**Comment by Canop** [comment]
There's now a release tag
